from collections.abc import AsyncIterator, Mapping, Sequence
from datetime import datetime
from types import TracebackType
from typing import Protocol, Self

from network_monitor_tds.domain.devices.models import Device
from network_monitor_tds.domain.events.models import DeviceEvent
from network_monitor_tds.domain.network.models import MacAddress
from network_monitor_tds.domain.observations.models import Detection, Fact
from network_monitor_tds.domain.plugins.models import PluginConfig, PluginId
from network_monitor_tds.domain.presence.models import Presence, PresenceInterval


class DeviceRepository(Protocol):
    async def get(self, mac: MacAddress) -> Device | None: ...
    async def list(self) -> Sequence[Device]: ...
    async def save(self, device: Device) -> None: ...


class FactRepository(Protocol):
    async def for_device(self, mac: MacAddress) -> dict[str, Fact]: ...
    async def all(self) -> dict[MacAddress, dict[str, Fact]]: ...
    async def save(self, mac: MacAddress, facts: Mapping[str, Fact]) -> None: ...


class DetectionRepository(Protocol):
    async def for_device(self, mac: MacAddress) -> dict[PluginId, Detection]: ...
    async def save(self, mac: MacAddress, detection: Detection) -> None: ...


class PresenceRepository(Protocol):
    async def get(self, mac: MacAddress) -> Presence | None: ...
    async def all(self) -> dict[MacAddress, Presence]: ...
    async def save(self, mac: MacAddress, presence: Presence) -> None: ...
    async def open_interval(self, mac: MacAddress, start: datetime) -> None: ...
    async def close_interval(self, mac: MacAddress, end: datetime) -> None: ...
    async def intervals_since(
        self, since: datetime
    ) -> dict[MacAddress, list[PresenceInterval]]: ...


class EventRepository(Protocol):
    async def add(self, event: DeviceEvent) -> None: ...
    async def recent(self, limit: int) -> Sequence[DeviceEvent]: ...


class PluginConfigRepository(Protocol):
    async def get(self, plugin_id: PluginId) -> PluginConfig | None: ...
    async def list(self) -> Sequence[PluginConfig]: ...
    async def save(self, config: PluginConfig) -> None: ...


class UnitOfWork(Protocol):
    @property
    def devices(self) -> DeviceRepository: ...
    @property
    def facts(self) -> FactRepository: ...
    @property
    def detections(self) -> DetectionRepository: ...
    @property
    def presence(self) -> PresenceRepository: ...
    @property
    def events(self) -> EventRepository: ...
    @property
    def plugin_configs(self) -> PluginConfigRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...


class EventPublisher(Protocol):
    def publish(self, event: DeviceEvent) -> None: ...


class EventSubscriber(Protocol):
    def subscribe(self) -> AsyncIterator[DeviceEvent]: ...
